### ISSUE TITLE
add siamese cat

### ISSUE THREAD

**Issue by SiDjackWasTaken** [DBTDerpbox/LCE-Skin-Packs-Figura#2]

**Comment by DBTDerpbox** [comment]
for whenever i get the motivation to start porting these again, what pack is this skin from?

**Comment by SiDjackWasTaken** [comment]
battle and beasts 2

**Comment by DBTDerpbox** [comment]
completed by 3ae205863626e68b5448f1af3b84ab9ff7e22341
